Remove App switcher
RedHatInsights/insights-chrome pull request #1105
Opened 2021-01-04 11:48 UTC by PanSpagetka

https://issues.redhat.com/browse/RHCLOUD-10692

2021-01-04 12:01 UTC, Hyperkid123 commented
Merge only after https://github.com/RedHatInsights/insights-chrome/pull/1101 (contains additional travis config to not publish to QA)

2021-01-04 13:18 UTC, ryelo commented
@PanSpagetka We'll want to remove the bundle switcher, which you've done, but we still need to leave the "title" of the bundle where that area was, just remove the dropdown portion of it

2021-01-05 12:21 UTC, Hyperkid123 commented
@PanSpagetka can you rebase the branch?

2021-01-12 09:04 UTC, Hyperkid123 submitted a review, later dismissed

2021-01-12 19:01 UTC, karelhala reviewed
Looking good! Just a few changes to use PF vars instead of direct values.

2021-01-12 19:01 UTC, karelhala commented on src/js/App/Sidenav/SideNav.scss
> +    border-bottom: 3px solid #3c3f42;
Can you change this to use PF css vars?
```suggestion
    border-bottom: var(--pf-global--spacer--xs) solid var(--pf-global--Color--300);
```

2021-01-12 19:01 UTC, karelhala commented on src/js/App/Sidenav/SideNav.scss
> +    margin-top: 7px;
```suggestion
    margin-top: var(--pf-global--spacer--sm);
```

2021-01-12 19:27 UTC, ryelo requested changes
Can you line up the left side of the Bundle name with the rest of the left most content (hamburger + items in the nav)?

2021-01-14 13:11 UTC, karelhala approved these changes

2021-01-14 13:57 UTC, ryelo approved these changes

2021-01-14 14:43 UTC, merged