track Pendo ad blocking
RedHatInsights/insights-chrome pull request #1122
Opened 2021-01-14 11:28 UTC by PanSpagetka

https://issues.redhat.com/browse/RHCLOUD-9700

2021-01-14 11:39 UTC, Hyperkid123 reviewed
Instead of doing multiple requests for the same resource, we could also try using the `onerror` handler.
```jsx
s.onerror = function(error){console.log(error, 'error')}
```

In this case you could add that callback to here
```jsx
(v[w]);y=e.createElement(n);y.async=!0;y.src=`https://content.analytics.cloud.redhat.com/agent/static/${API_KEY}/pendo.js`
```
Targeting the "y" element.
```
y.onerror = function(error){log('Pendo blocked')}
```

2021-01-14 11:59 UTC, PanSpagetka commented
@Hyperkid123 Thanks! It seems to work and it is much nicer!

2021-01-14 13:46 UTC, ryelo requested changes
Instead of doing a regular log, can you either throw a console.error or log it to Sentry that way we can gather the metrics in sentry?

2021-01-18 14:04 UTC, ryelo approved these changes

2021-01-18 14:13 UTC, merged