Fix spacing for external links
RedHatInsights/insights-chrome pull request #1349
Opened 2021-04-20 11:19 UTC by PanSpagetka

2021-04-20 12:08 UTC, Hyperkid123 commented on src/js/App/Sidenav/__snapshots__/NavigationItem.test.js.snap
> +      class="pf-c-nav__link undefined "
We are adding some undefined classnames here. You could use the `classNames` lib to avoid these.

2021-04-20 12:23 UTC, Hyperkid123 commented
@PanSpagetka can you provide a screen? I am too lazy to check it locally.

2021-04-20 14:19 UTC, ryelo approved these changes

2021-04-20 14:20 UTC, ryelo requested changes

2021-04-20 14:20 UTC, ryelo commented on src/js/App/Sidenav/SectionNav.scss
> +                  margin-left: var(--pf-global--spacer--sm)
Missing `;`

2021-04-20 14:20 UTC, ryelo commented on src/js/App/Sidenav/SectionNav.scss
> +        padding-left: var(--pf-global--spacer--lg)
missing `;`

2021-04-21 13:00 UTC, karelhala approved these changes

2021-04-21 13:06 UTC, ryelo approved these changes

2021-04-21 13:06 UTC, merged