Fixed redirect to landing page from beta app
RedHatInsights/insights-chrome pull request #1428
Opened 2021-05-12 21:30 UTC by arivepr

This is closing Jira card#: 14008

2021-05-13 18:52 UTC, ryelo requested changes

2021-05-13 18:52 UTC, ryelo commented on src/js/App/Header/Tools.js
> +  const isAppOnlyOnBeta = store.getState().chrome.activeSection.isBeta;
need to use a optional chaining here:
 ```suggestion
  const isAppOnlyOnBeta = store.getState().chrome.activeSection?.isBeta;
```

2021-05-26 18:32 UTC, ryelo requested changes

2021-05-26 18:32 UTC, ryelo commented on src/js/App/Header/Tools.js
> +  const isAppOnlyOnBeta = store.getState().chrome.activeSection?.isBeta; // eslint-disable-line
we shouldn't disable eslint on this line

2021-06-03 07:08 UTC, Hyperkid123 approved these changes

2021-06-03 07:08 UTC, merged