Removed unecessary ReactDOM.render calls
RedHatInsights/insights-chrome pull request #1929
Opened 2022-06-17 10:47 UTC by radekkaluzik

https://issues.redhat.com/browse/RHCLOUD-15881

2022-06-17 14:06 UTC, radekkaluzik commented on src/js/App/Header/index.js
> -import React, { lazy, Suspense, Fragment } from 'react';
ok, done

2022-06-17 14:16 UTC, Hyperkid123 requested changes

2022-06-17 14:16 UTC, Hyperkid123 commented on src/js/App/Header/index.js
> -import React, { lazy, Suspense, Fragment } from 'react';
The file is still referenced in `src/js/chrome/render-chrome.js`. The build fails. We don't need anything from this file anymore.
```
import { headerLoader } from '../App/Header';
```

2022-06-20 14:26 UTC, Hyperkid123 approved these changes

2022-06-21 07:50 UTC, merged