[RHINENG-663] - Use Product as subtitle in AllServices
RedHatInsights/insights-chrome pull request #2576
Opened 2023-07-18 23:39 UTC by AsToNlele

[RHINENG-663](https://issues.redhat.com/browse/RHINENG-663)

Is it possible to use the `product` field for the subtitle here?
![image](https://github.com/RedHatInsights/insights-chrome/assets/20592948/f03792a0-bd5d-4bab-9f18-6cea501aeb13)
At first I tried changing the bundle names, but that would not work for some ansible items

https://github.com/RedHatInsights/chrome-service-backend/pull/228 depends on this PR

2023-07-19 06:59 UTC, Hyperkid123 requested changes
> Is it possible to use the product field for the subtitle here?

@AsToNlele unfortunately we can't as it would impact other tiles that do want to use the product as a subtitle and have the product defined in their links. I would suggest creating a new attribute inside the Chrome service as that instead.

2023-07-20 09:43 UTC, AsToNlele commented
I've added `subtitle` property

2023-07-20 10:21 UTC, Hyperkid123 commented on src/components/AllServicesDropdown/AllServicesGalleryLink.tsx
> +            <Text component="small">{subtitle ? subtitle : bundle !== title ? bundle : null}</Text>
Can you change this to not use multiple ternary statements? To something like
```JS
subtitle || (bundle !== title ? bundle : null)
```

2023-07-20 11:51 UTC, Hyperkid123 approved these changes

2023-07-20 11:52 UTC, merged