Add section on how to run local chrome
RedHatInsights/insights-chrome pull request #984
Opened 2020-09-23 12:22 UTC by karelhala

2020-09-23 12:33 UTC, ryelo requested changes

2020-09-23 12:33 UTC, ryelo commented on README.md
> +After permorming these tasks you can access `ci.cloud.redhat.com:1337/insights/starter` and observe changes as you save them.
should be ci.foo

2020-09-23 13:21 UTC, karelhala commented on README.md
> +After permorming these tasks you can access `ci.cloud.redhat.com:1337/insights/starter` and observe changes as you save them.
Good point, fixed!

2020-09-24 18:27 UTC, ryelo approved these changes

2020-09-24 18:27 UTC, merged